sudo: required
language: node_js
services:
  - docker
install: true
before_script:
  - echo "NODE_ENV=$NODE_ENV" >> .env
  - echo "SD_API_URL=$SD_API_URL" >> .env
  - echo "TMC_API_URL=$TMC_API_URL" >> .env
  - echo "TMC_ADMIN_ACCESS_TOKEN=$TMC_ADMIN_ACCESS_TOKEN" >> .env
  - echo "MONGO_DB=$MONGO_DB" >> .env
  - docker-compose -f docker-compose.ci.yml up -d
script:
  - bash ./run-tests.sh
after_script:
  - docker-compose down
