sudo: required
language: node_js
services:
  - docker
install:
before_script:
  - echo "{}" > ./rev-manifest.json
  - docker-compose up -d
script:
  - bash ./run-tests.sh
after_script:
  - docker-compose down
