FROM node:6.8

RUN mkdir -p /student-dashboard/src

WORKDIR /student-dashboard/src

COPY ./package.json /student-dashboard/src

RUN npm install

COPY . /student-dashboard/src

EXPOSE 3000

CMD npm run-script dev
