export const CLOSE_PLUGIN = 'CLOSE_PLUGIN';
export const OPEN_PLUGIN = 'OPEN_PLUGIN';
export const CHANGE_EXERCISE_GROUP = 'CHANGE_EXERCISE_GROUP';
export const OPEN_EXPLANATION = 'OPEN_EXPLANATION';
export const CLOSE_EXPLANATION = 'CLOSE_EXPLANATION';
export const OPEN_PAGE = 'OPEN_PAGE';
export const OPEN_GRADE_ESTIMATE = 'OPEN_GRADE_ESTIMATE';
export const CLOSE_GRADE_ESTIMATE = 'CLOSE_GRADE_ESTIMATE';
