export const RADAR_VISUALIZATION = 'RADAR_VISUALIZATION';
export const RADAR_VISUALIZATION_WITH_GRADE = 'RADAR_VISUALIZATION_WITH_GRADE';
export const TEXTUAL_VISUALIZATION = 'TEXTUAL_VISUALIZATION';
export const TEXTUAL_VISUALIZATION_WITH_GRADE = 'TEXTUAL_VISUALIZATION_WITH_GRADE';
export const NO_VISUALIZATION = 'NO_VISUALIZATION';

export const radarVisualizationTypes = [
  RADAR_VISUALIZATION,
  RADAR_VISUALIZATION_WITH_GRADE
];

export const textualVisualizationTypes = [
  TEXTUAL_VISUALIZATION,
  TEXTUAL_VISUALIZATION_WITH_GRADE
];

export const gradeEstimateTypes = [
  RADAR_VISUALIZATION_WITH_GRADE,
  TEXTUAL_VISUALIZATION_WITH_GRADE
];
